version: '3'

services:
  crp:
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - ./:/project
    container_name: crp
    OPENAI_API_KEY: ${OPENAI_API_KEY}
    BEARER_TOKEN: ${BEARER_TOKEN}
#    ports:
#        - "8080:8080"
    tty: true
    stdin_open: true