FROM python:3.10

RUN apt-get update
RUN pip install --upgrade pip

# ref: https://github.com/Guandaline/chatgpt-retrieval-plugin/commit/f7300c27de86e5481511dcbcd8e33a05b222ecc3#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557
RUN apt-get install -y gcc curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
SHELL ["bash", "-lc"]

RUN pip install poetry
WORKDIR /app
COPY . /app
RUN poetry install