FROM python:3.10

RUN apt-get update
RUN pip install --upgrade pip

RUN apt-get install -y gcc curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
SHELL ["bash", "-lc"]

RUN pip install poetry
WORKDIR /app
COPY . /app
RUN poetry install